Feat/sqs 2 dc s3
opendatacube/datacube-index pull request #71
Opened 2020-08-25 07:25 UTC by pindge

- branch out to include index by yaml definition in s3 bucket
- add test case
- add typedef

2020-08-25 21:35 UTC, sachitrajbhandari commented on tests/test_sqs_to_dc.py
> +    assert uri == "http://{bucket_name}.s3.amazonaws.com/{obj_key}".format(
How about using `get_s3_url` function here?

2020-08-25 21:35 UTC, sachitrajbhandari commented on odc_index/sqs_to_dc.py
> +    "--prefix",
Only `prefix` as an option name is not that clear. What do you think of `s3-prefix` for any other meaningful option name?

2020-08-25 21:35 UTC, sachitrajbhandari commented on odc_index/sqs_to_dc.py
> +                # NRT data may not have a creation_dt, attempt insert if missing
This function `get_metadata_s3_object` can be generic to be used for any messages that contains S3 links. Do we need to add `creation_dt` for all dataset if not can we make it conditional?

2020-08-25 22:56 UTC, alexgleith requested changes

2020-08-25 22:56 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
I'd love to solve this problem more specifically rather than patching it at index time...

Hey @whatnick can we look at resolving it at the source?

2020-08-25 22:56 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +    "--prefix",
Can we include an example in the help of what a prefix would look like too please?

2020-08-25 22:56 UTC, alexgleith commented on tests/test_sqs_to_dc.py
> +SENTINEL_2_NRT_PREFIX = ("L2/sentinel-2-nrt/S2MSIARD/*/*/ARD-METADATA.yaml",)
This is not really a prefix, it's more a 'path template' or something like that.

2020-08-25 22:56 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +        raise SQStoDCException("Message did not contain S3 records")
Raising exceptions is nice, but, this will end the current queue iteration, which may not be wanted.

2020-08-25 22:56 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +            except Exception as e:
Also exception raising here will kill the process.

What if there's one bad message, and we don't want to end, just ignore it?

2020-08-25 22:56 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +        bucket_name = record["s3"]["bucket"]["name"]
Doing a record.get() here is more robust and won't throw an exception if the field isn't missing. Check out the toolz function...

2020-08-25 23:09 UTC, pindge commented on tests/test_sqs_to_dc.py
> +SENTINEL_2_NRT_PREFIX = ("L2/sentinel-2-nrt/S2MSIARD/*/*/ARD-METADATA.yaml",)
would it be fair to call it `metadata-s3-file-path`

2020-08-25 23:13 UTC, alexgleith commented on tests/test_sqs_to_dc.py
> +SENTINEL_2_NRT_PREFIX = ("L2/sentinel-2-nrt/S2MSIARD/*/*/ARD-METADATA.yaml",)
I think that naming the functions and arguments is important, so that the code is self-documenting.

The function `get_metadata_s3_object` probably should be called something like `get_metadata_from_s3_record` and then it can match on `record_path` rather than `prefix` maybe? Does that make it clearer, you think?

2020-08-26 00:47 UTC, whatnick commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
WAGL NRT container is pretty immutable currently. So fixing it at the source is hard, perhaps @uchchwhash will get to it. The possible solution is at the sink with @jeremyh . Also consider this is an OpenDataCube project and DEA shortcomings / hacks should not hobble it.

2020-08-26 01:18 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
>should not hobble it

Do you mean should _not_ be included?

2020-08-26 02:44 UTC, pindge commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
I updated the code to better handle this, but it is still in. Thats my take on the discussion

2020-08-26 03:51 UTC, sachitrajbhandari commented on odc_index/sqs_to_dc.py
> +            bucket_name = record.get("s3").get("bucket").get("name")
Here, if `s3` or `bucket` is missing, it will throw an exception. 
Either supply empty dict as default value 
`bucket_name = record.get("s3", {}).get("bucket", {}).get("name")` 
or use function from toolz 
`bucket_name = dicttoolz.get_in(['s3', 'bucket', 'name'], record)`

2020-08-26 05:07 UTC, jeremyh commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
If we’re going to patch the NRT data like this, it would be better to use system_information→time_processed, as that’s the correct “creation time”, not extent→center_time.

2020-08-26 05:12 UTC, jeremyh commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
But a cleaner way is to change the metadata type to eo-plus, so we don’t have to patch it at all.

2020-08-26 06:47 UTC, pindge commented on odc_index/sqs_to_dc.py
> +            bucket_name = record.get("s3").get("bucket").get("name")
ok, i see i was wondering how is dicttoolz any useful here

2020-08-26 07:02 UTC, pindge commented on odc_index/sqs_to_dc.py
> +                        data["creation_dt"] = data["extent"]["center_dt"]
changed to use `system_information time_processed`

2020-08-31 02:49 UTC, alexgleith commented on odc_index/sqs_to_dc.py
> +                                data = dicttoolz.assoc(data, "creation_dt", creation_dt)
I don't think that we should be patching bad metadata with this tool.
```suggestion
```

2020-08-31 07:05 UTC, pindge commented on odc_index/sqs_to_dc.py
> +                                data = dicttoolz.assoc(data, "creation_dt", creation_dt)
Your point is valid, if we want this to be generic for standard s3 record to be processed, not include this buggy patch is the right choice

2020-08-31 07:06 UTC, pindge commented on odc_index/sqs_to_dc.py
> +                                data = dicttoolz.assoc(data, "creation_dt", creation_dt)
@whatnick what should we do about this then, both long run and short run

2020-09-01 01:21 UTC, alexgleith reviewed
Sorry, but I still think that documenting only half the functionality is misleading...

I'd prefer the documentation to be in a separate PR.

2020-09-01 23:45 UTC, pindge commented
> Sorry, but I still think that documenting only half the functionality is misleading...
> 
> I'd prefer the documentation to be in a separate PR.

Unless someone who knows the majority of the code base and how to use it take a lead on starting the documentation and I can add this bit of doc to it.

Or, add this in and then tidy it up as doc gets created for the majority. This bit cannot go anywhere, by the time we get to it, it could easily be forgotten.

2020-09-02 00:00 UTC, alexgleith commented
>Unless someone who knows the majority of the code base and how to use it take a lead on starting the documentation and I can add this bit of doc to it.

Hey @pindge if you remove the docs and add them in a separate PR, I'll help by documenting the other functions. I just don't want half of one of the four tools documented, as it's misleading. :-)

2020-09-02 00:06 UTC, sachitrajbhandari commented
> > Unless someone who knows the majority of the code base and how to use it take a lead on starting the documentation and I can add this bit of doc to it.
> 
> Hey @pindge if you remove the docs and add them in a separate PR, I'll help by documenting the other functions. I just don't want half of one of the four tools documented, as it's misleading. :-)

Let's create a new PR and I will add documentation for rest of the part of SQS_to_DC tool excluding Pin's work.

2020-09-02 01:26 UTC, pindge commented
> > Unless someone who knows the majority of the code base and how to use it take a lead on starting the documentation and I can add this bit of doc to it.
> 
> Hey @pindge if you remove the docs and add them in a separate PR, I'll help by documenting the other functions. I just don't want half of one of the four tools documented, as it's misleading. :-)

ok, removed

2020-09-03 06:50 UTC, alexgleith approved these changes

2020-09-03 06:50 UTC, merged